---
- hosts: ubuntu
  roles:

    - python
    - java

    - role: Change-motd
      vars:
        motd: "Ansible Namage node by jmczaens-tip"

    - role: Create-user
      vars:
        username: "jmczaens-tip"
        name: "Jose Mari C. Zaens"
